### ISSUE TITLE
Add vignettes to better illustrate how to use REndo

### ISSUE THREAD

**Issue by mmeierer** [mmeierer/REndo#28]

**Comment by pschil** [comment]
Commit b7cc8c755c27cdbf5a351390d77df5ece133e499 on the `development` branch adds the necessary infrastructure for building the vignette. More info on vignettes [here.](http://r-pkgs.had.co.nz/vignettes.html#vignette-workflow-2)

Vignette file is the markdown file `REndo-introduction.Rmd` in folder `./vignettes`

`knit` the markdown for reviewien. To actually include it in the package, run `devtools::build_vignettes()` and then rebuild and install.
