### ISSUE TITLE
Compatibility with R 4.0.2

### ISSUE THREAD

**Issue by gwcottle** [mmeierer/REndo#54]
Recently upgraded from R 3.6.3 and the multilevelIV function has stopped working. The only message returned is "Error: The above errors were encountered!" Are you aware of any compatibility issues?

**Comment by pschil** [comment]
Thanks for reporting. We are currently not aware of any specific issues with multilevelIV and I can run the examples on R 4.0.1 on OsX. 

Do you have any more information on how to reproduce this issue?
The full message, some code with a reproducible example, and the output from `sessionInfo()` would be very helpful.

Mind though that if something is wrong with your input (such as a misspecified formula, NA in the data, etc), all methods in REndo are aborted with `"Error: The above errors were encountered!"` and right above this text, it is described, also in red print, what is wrong and why the function stopped.

**Comment by gwcottle** [comment]
NA in the data! Missed that when I was looking through the error code. Thanks
